# Generated by Django 4.0 on 2022-04-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('course', '0002_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved',
            old_name='cource',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='saved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cource', to='account.user'),
        ),
    ]
