# Generated by Django 4.0 on 2022-05-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_name'),
        ('course', '0007_remove_saved_saved_alter_saved_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='saved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_p', to='account.user'),
        ),
    ]
