# Generated by Django 3.2.7 on 2022-07-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='dani loh', null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
