# Generated by Django 3.2.7 on 2022-07-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default=None, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
