# Generated by Django 3.2.7 on 2022-07-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20220706_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
