# Generated by Django 4.0 on 2022-05-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_remove_user_username_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/user_image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_user', to='account.user')),
            ],
            options={
                'verbose_name': 'Info user',
                'verbose_name_plural': 'Info users',
            },
        ),
    ]
